spring:
  datasource:
    url: "jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1;MODE=MySQL"
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /api
